# Site settings
title:
email: ashley.fowler@mssm.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "mssmcmca.github.io/FCON.github.io/" # the base hostname & protocol for your site
twitter_username: 
github_username:  MSSMCMCA 
array: []

# Build settings
markdown: kramdown

collections:
  instructors:
    output: true
  workshops:
    output: true
  news:
    output: true
